'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditPeriodDates

    '''<summary>
    '''pnlHasAccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlHasAccess As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rap1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rap1 As Global.Telerik.Web.UI.RadAjaxPanel

    '''<summary>
    '''pnlEnterSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEnterSite As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblNoRecs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoRecs As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbSiteNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSiteNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbAgencyCd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAgencyCd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSubmitSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitSite As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlEditDates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEditDates As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbReturn As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblSiteNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSiteNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rsPeriodDates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rsPeriodDates As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''rpPeriods control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpPeriods As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''phPeriods control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phPeriods As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''rsb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rsb As Global.Telerik.Web.UI.RadSplitBar

    '''<summary>
    '''rpEditDates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpEditDates As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''pnlInstructions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInstructions As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEdit As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlEditDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEditDate As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ltlRecordType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltlRecordType As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''rttSlider control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rttSlider As Global.Telerik.Web.UI.RadToolTip

    '''<summary>
    '''pnlEndBeginDates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEndBeginDates As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblSlider1StartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSlider1StartDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rsEndBeginDates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rsEndBeginDates As Global.Telerik.Web.UI.RadSlider

    '''<summary>
    '''lblSlider1EndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSlider1EndDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEndDate As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblSlider2StartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSlider2StartDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rsEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rsEndDate As Global.Telerik.Web.UI.RadSlider

    '''<summary>
    '''lblSlider2EndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSlider2EndDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ltlPeriodID1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltlPeriodID1 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltlBegDate1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltlBegDate1 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lblEndDate1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEndDate1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ltlStatus1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltlStatus1 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltlPeriodID2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltlPeriodID2 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lblBegDate2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBegDate2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEndDate2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEndDate2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ltlStatus2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltlStatus2 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''btnEditDates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditDates As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hfDatesEdited control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfDatesEdited As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfDateType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfDateType As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''pnlConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlConfirm As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As SIMS.RMS
        Get
            Return CType(MyBase.Master, SIMS.RMS)
        End Get
    End Property
End Class
