'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ElemReport

    '''<summary>
    '''ram control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ram As Global.Telerik.Web.UI.RadAjaxManager

    '''<summary>
    '''ralp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ralp As Global.Telerik.Web.UI.RadAjaxLoadingPanel

    '''<summary>
    '''pnlSystem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSystem As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rts1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rts1 As Global.Telerik.Web.UI.RadTabStrip

    '''<summary>
    '''rmp1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rmp1 As Global.Telerik.Web.UI.RadMultiPage

    '''<summary>
    '''rpv0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpv0 As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''rpbInstructions1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpbInstructions1 As Global.Telerik.Web.UI.RadPanelBar

    '''<summary>
    '''rgApprove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgApprove As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''rpv1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpv1 As Global.Telerik.Web.UI.RadPageView

    '''<summary>
    '''rpbInstructions2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpbInstructions2 As Global.Telerik.Web.UI.RadPanelBar

    '''<summary>
    '''ltlActiveSiteToggle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltlActiveSiteToggle As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lbActiveSiteToggle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbActiveSiteToggle As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''rgAllSites control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgAllSites As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As SIMS.SIMSSafety
        Get
            Return CType(MyBase.Master, SIMS.SIMSSafety)
        End Get
    End Property
End Class
