'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EvalMaps

    '''<summary>
    '''upMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upMain As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlMap_Canvas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMap_Canvas As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlTopFilterControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTopFilterControls As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ddlEvalOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEvalOptions As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlWSC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlWSC As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnTopFilters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTopFilters As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlSideFilterControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSideFilterControls As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlNotice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNotice As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlNoticeIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNoticeIP As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblNotice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNotice As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlFilters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFilters As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlDisplayOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDisplayOptions As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblOffice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOffice As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlOffice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOffice As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblFieldTrip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFieldTrip As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlFieldTrip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFieldTrip As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnlResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlResults As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlResultsIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlResultsIP As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblResultsSum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResultsSum As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblResultsCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResultsCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hlResultsList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlResultsList As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lblWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWarning As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlLegend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLegend As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlLegendIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLegendIP As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMap As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''GMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GMap As Global.Subgurim.Controles.GMap

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As SIMS.SIMSSiteTopLevel
        Get
            Return CType(MyBase.Master, SIMS.SIMSSiteTopLevel)
        End Get
    End Property
End Class
