'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RecordConfig

    '''<summary>
    '''pnlError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlHasAccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlHasAccess As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''upMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upMain As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlRecordNotUsed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRecordNotUsed As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cbReactivate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbReactivate As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlContOrNoncont control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlContOrNoncont As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlBoth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBoth As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cbCont control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbCont As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbNonContDD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbNonContDD As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbNoncont control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbNoncont As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlOnlyNoncont control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOnlyNoncont As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cbOnlyNoncont control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbOnlyNoncont As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlUpdateConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUpdateConfirm As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblRecordTypeAU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRecordTypeAU As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hlStationInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlStationInfo As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''gvOtherRecordsAU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvOtherRecordsAU As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''pnlRecordConfigForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRecordConfigForm As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblRecordType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRecordType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblContRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblContRecord As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDDHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDDHelp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cblUsedDDs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblUsedDDs As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''cbMultiDDs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMultiDDs As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cblUnusedDDs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblUnusedDDs As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''cvDDList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvDDList As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''lblRecordTypeHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRecordTypeHelp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRecordTypeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRecordTypeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlRecordType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRecordType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvRecordType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvRecordType As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblCategoryHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategoryHelp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCategoryNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategoryNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlCategoryNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCategoryNo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvCategoryNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCategoryNo As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''pnlCatReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCatReason As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblCategoryReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCategoryReason As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUpdateReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUpdateReason As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlUpdateReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlUpdateReason As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvUpdateReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvUpdateReason As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblUpdateOtherReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUpdateOtherReason As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbUpdateOtherReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbUpdateOtherReason As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlCatReasonNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCatReasonNew As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblNewReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewReason As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlNewReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNewReason As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvNewReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvNewReason As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblNewOtherReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewOtherReason As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbNewOtherReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbNewOtherReason As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOperator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOperator As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnlFieldTrips control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFieldTrips As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''blFieldTrips control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents blFieldTrips As Global.System.Web.UI.WebControls.BulletedList

    '''<summary>
    '''ddlChecker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlChecker As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlReviewer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlReviewer As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblReviewerEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewerEmail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblResponsibleOffice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResponsibleOffice As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbResponsibleOffice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbResponsibleOffice As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''cbNotPublished control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbNotPublished As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cbNotUsed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbNotUsed As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnReset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReset As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbOtherRecords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbOtherRecords As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''imgOtherRecords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgOtherRecords As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''pnlOtherRecords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOtherRecords As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''gvOtherRecords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvOtherRecords As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblTest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTest As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hfRMSSiteID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfRMSSiteID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfTSType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfTSType As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''cpe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpe As Global.AjaxControlToolkit.CollapsiblePanelExtender

    '''<summary>
    '''rce0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rce0 As Global.AjaxControlToolkit.RoundedCornersExtender

    '''<summary>
    '''rce1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rce1 As Global.AjaxControlToolkit.RoundedCornersExtender

    '''<summary>
    '''rce2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rce2 As Global.AjaxControlToolkit.RoundedCornersExtender

    '''<summary>
    '''rec3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rec3 As Global.AjaxControlToolkit.RoundedCornersExtender

    '''<summary>
    '''rec4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rec4 As Global.AjaxControlToolkit.RoundedCornersExtender

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As SIMS.RMS
        Get
            Return CType(MyBase.Master, SIMS.RMS)
        End Get
    End Property
End Class
