'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RecordProcessing

    '''<summary>
    '''pnlHasAccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlHasAccess As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rapMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rapMain As Global.Telerik.Web.UI.RadAjaxPanel

    '''<summary>
    '''lblListType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblListType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ltlQuickLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltlQuickLinks As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''hfListType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfListType As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''phRecordsToProcess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phRecordsToProcess As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As SIMS.RMS
        Get
            Return CType(MyBase.Master, SIMS.RMS)
        End Get
    End Property
End Class
