'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace PASSService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="PASSSite", [Namespace]:="http://schemas.datacontract.org/2004/07/WCFServices"),  _
     System.SerializableAttribute()>  _
    Partial Public Class PASSSite
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AgencyCdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AntennaHeightField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AssignedByField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AssignedDateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DBNoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DCPIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DeployDateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DistrictCdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ModifiedByField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ModifiedDateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NWISHostField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NWISWebSiteIDField As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OtherSitesField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AgencyCd() As String
            Get
                Return Me.AgencyCdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AgencyCdField, value) <> true) Then
                    Me.AgencyCdField = value
                    Me.RaisePropertyChanged("AgencyCd")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AntennaHeight() As String
            Get
                Return Me.AntennaHeightField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AntennaHeightField, value) <> true) Then
                    Me.AntennaHeightField = value
                    Me.RaisePropertyChanged("AntennaHeight")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AssignedBy() As String
            Get
                Return Me.AssignedByField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AssignedByField, value) <> true) Then
                    Me.AssignedByField = value
                    Me.RaisePropertyChanged("AssignedBy")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AssignedDate() As Date
            Get
                Return Me.AssignedDateField
            End Get
            Set
                If (Me.AssignedDateField.Equals(value) <> true) Then
                    Me.AssignedDateField = value
                    Me.RaisePropertyChanged("AssignedDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DBNo() As String
            Get
                Return Me.DBNoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DBNoField, value) <> true) Then
                    Me.DBNoField = value
                    Me.RaisePropertyChanged("DBNo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DCPID() As String
            Get
                Return Me.DCPIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DCPIDField, value) <> true) Then
                    Me.DCPIDField = value
                    Me.RaisePropertyChanged("DCPID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DeployDate() As Date
            Get
                Return Me.DeployDateField
            End Get
            Set
                If (Me.DeployDateField.Equals(value) <> true) Then
                    Me.DeployDateField = value
                    Me.RaisePropertyChanged("DeployDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DistrictCd() As String
            Get
                Return Me.DistrictCdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DistrictCdField, value) <> true) Then
                    Me.DistrictCdField = value
                    Me.RaisePropertyChanged("DistrictCd")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID() As Integer
            Get
                Return Me.IDField
            End Get
            Set
                If (Me.IDField.Equals(value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ModifiedBy() As String
            Get
                Return Me.ModifiedByField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ModifiedByField, value) <> true) Then
                    Me.ModifiedByField = value
                    Me.RaisePropertyChanged("ModifiedBy")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ModifiedDate() As Date
            Get
                Return Me.ModifiedDateField
            End Get
            Set
                If (Me.ModifiedDateField.Equals(value) <> true) Then
                    Me.ModifiedDateField = value
                    Me.RaisePropertyChanged("ModifiedDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NWISHost() As String
            Get
                Return Me.NWISHostField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NWISHostField, value) <> true) Then
                    Me.NWISHostField = value
                    Me.RaisePropertyChanged("NWISHost")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NWISWebSiteID() As System.Nullable(Of Decimal)
            Get
                Return Me.NWISWebSiteIDField
            End Get
            Set
                If (Me.NWISWebSiteIDField.Equals(value) <> true) Then
                    Me.NWISWebSiteIDField = value
                    Me.RaisePropertyChanged("NWISWebSiteID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Number() As String
            Get
                Return Me.NumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NumberField, value) <> true) Then
                    Me.NumberField = value
                    Me.RaisePropertyChanged("Number")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OtherSites() As String
            Get
                Return Me.OtherSitesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OtherSitesField, value) <> true) Then
                    Me.OtherSitesField = value
                    Me.RaisePropertyChanged("OtherSites")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="PASSService.IPASSService")>  _
    Public Interface IPASSService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPASSService/GetAllSites", ReplyAction:="http://tempuri.org/IPASSService/GetAllSitesResponse")>  _
        Function GetAllSites() As PASSService.PASSSite()
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IPASSServiceChannel
        Inherits PASSService.IPASSService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PASSServiceClient
        Inherits System.ServiceModel.ClientBase(Of PASSService.IPASSService)
        Implements PASSService.IPASSService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetAllSites() As PASSService.PASSSite() Implements PASSService.IPASSService.GetAllSites
            Return MyBase.Channel.GetAllSites
        End Function
    End Class
End Namespace
