//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMS2017.SIMSService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Site", Namespace="http://schemas.datacontract.org/2004/07/WCFServices")]
    [System.SerializableAttribute()]
    public partial class Site : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgencyCdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DBNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIMS2017.SIMSService.Element[] ElementsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NWISHostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> NWISWebSiteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfficeCdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OfficeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfficeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WSCCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WSCNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgencyCd {
            get {
                return this.AgencyCdField;
            }
            set {
                if ((object.ReferenceEquals(this.AgencyCdField, value) != true)) {
                    this.AgencyCdField = value;
                    this.RaisePropertyChanged("AgencyCd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DBNo {
            get {
                return this.DBNoField;
            }
            set {
                if ((object.ReferenceEquals(this.DBNoField, value) != true)) {
                    this.DBNoField = value;
                    this.RaisePropertyChanged("DBNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIMS2017.SIMSService.Element[] Elements {
            get {
                return this.ElementsField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementsField, value) != true)) {
                    this.ElementsField = value;
                    this.RaisePropertyChanged("Elements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NWISHost {
            get {
                return this.NWISHostField;
            }
            set {
                if ((object.ReferenceEquals(this.NWISHostField, value) != true)) {
                    this.NWISHostField = value;
                    this.RaisePropertyChanged("NWISHost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> NWISWebSiteID {
            get {
                return this.NWISWebSiteIDField;
            }
            set {
                if ((this.NWISWebSiteIDField.Equals(value) != true)) {
                    this.NWISWebSiteIDField = value;
                    this.RaisePropertyChanged("NWISWebSiteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficeCd {
            get {
                return this.OfficeCdField;
            }
            set {
                if ((object.ReferenceEquals(this.OfficeCdField, value) != true)) {
                    this.OfficeCdField = value;
                    this.RaisePropertyChanged("OfficeCd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OfficeID {
            get {
                return this.OfficeIDField;
            }
            set {
                if ((this.OfficeIDField.Equals(value) != true)) {
                    this.OfficeIDField = value;
                    this.RaisePropertyChanged("OfficeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficeName {
            get {
                return this.OfficeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OfficeNameField, value) != true)) {
                    this.OfficeNameField = value;
                    this.RaisePropertyChanged("OfficeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WSCCode {
            get {
                return this.WSCCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.WSCCodeField, value) != true)) {
                    this.WSCCodeField = value;
                    this.RaisePropertyChanged("WSCCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WSCName {
            get {
                return this.WSCNameField;
            }
            set {
                if ((object.ReferenceEquals(this.WSCNameField, value) != true)) {
                    this.WSCNameField = value;
                    this.RaisePropertyChanged("WSCName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Element", Namespace="http://schemas.datacontract.org/2004/07/WCFServices")]
    [System.SerializableAttribute()]
    public partial class Element : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ElementIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ElementInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ElementNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIMS2017.SIMSService.ElementReportRef[] ElementReportRefsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportTypeCdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RevisedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> RevisedDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ElementID {
            get {
                return this.ElementIDField;
            }
            set {
                if ((this.ElementIDField.Equals(value) != true)) {
                    this.ElementIDField = value;
                    this.RaisePropertyChanged("ElementID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ElementInfo {
            get {
                return this.ElementInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementInfoField, value) != true)) {
                    this.ElementInfoField = value;
                    this.RaisePropertyChanged("ElementInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ElementName {
            get {
                return this.ElementNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementNameField, value) != true)) {
                    this.ElementNameField = value;
                    this.RaisePropertyChanged("ElementName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIMS2017.SIMSService.ElementReportRef[] ElementReportRefs {
            get {
                return this.ElementReportRefsField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementReportRefsField, value) != true)) {
                    this.ElementReportRefsField = value;
                    this.RaisePropertyChanged("ElementReportRefs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((this.PriorityField.Equals(value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportTypeCd {
            get {
                return this.ReportTypeCdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportTypeCdField, value) != true)) {
                    this.ReportTypeCdField = value;
                    this.RaisePropertyChanged("ReportTypeCd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RevisedBy {
            get {
                return this.RevisedByField;
            }
            set {
                if ((object.ReferenceEquals(this.RevisedByField, value) != true)) {
                    this.RevisedByField = value;
                    this.RaisePropertyChanged("RevisedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RevisedDate {
            get {
                return this.RevisedDateField;
            }
            set {
                if ((this.RevisedDateField.Equals(value) != true)) {
                    this.RevisedDateField = value;
                    this.RaisePropertyChanged("RevisedDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ElementReportRef", Namespace="http://schemas.datacontract.org/2004/07/WCFServices")]
    [System.SerializableAttribute()]
    public partial class ElementReportRef : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ElementIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportTypeCdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ElementID {
            get {
                return this.ElementIDField;
            }
            set {
                if ((this.ElementIDField.Equals(value) != true)) {
                    this.ElementIDField = value;
                    this.RaisePropertyChanged("ElementID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportTypeCd {
            get {
                return this.ReportTypeCdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportTypeCdField, value) != true)) {
                    this.ReportTypeCdField = value;
                    this.RaisePropertyChanged("ReportTypeCd");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SIMSService.ISIMSService")]
    public interface ISIMSService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISIMSService/GetAllSites", ReplyAction="http://tempuri.org/ISIMSService/GetAllSitesResponse")]
        SIMS2017.SIMSService.Site[] GetAllSites();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISIMSService/GetAllSites", ReplyAction="http://tempuri.org/ISIMSService/GetAllSitesResponse")]
        System.Threading.Tasks.Task<SIMS2017.SIMSService.Site[]> GetAllSitesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISIMSService/GetSiteByNumber", ReplyAction="http://tempuri.org/ISIMSService/GetSiteByNumberResponse")]
        SIMS2017.SIMSService.Site[] GetSiteByNumber(string site_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISIMSService/GetSiteByNumber", ReplyAction="http://tempuri.org/ISIMSService/GetSiteByNumberResponse")]
        System.Threading.Tasks.Task<SIMS2017.SIMSService.Site[]> GetSiteByNumberAsync(string site_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISIMSService/GetElementsBySite", ReplyAction="http://tempuri.org/ISIMSService/GetElementsBySiteResponse")]
        SIMS2017.SIMSService.Element[] GetElementsBySite(string site_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISIMSService/GetElementsBySite", ReplyAction="http://tempuri.org/ISIMSService/GetElementsBySiteResponse")]
        System.Threading.Tasks.Task<SIMS2017.SIMSService.Element[]> GetElementsBySiteAsync(string site_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISIMSService/GetElementsBySiteAndReport", ReplyAction="http://tempuri.org/ISIMSService/GetElementsBySiteAndReportResponse")]
        SIMS2017.SIMSService.Element[] GetElementsBySiteAndReport(string site_no, string agency_cd, string report_tp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISIMSService/GetElementsBySiteAndReport", ReplyAction="http://tempuri.org/ISIMSService/GetElementsBySiteAndReportResponse")]
        System.Threading.Tasks.Task<SIMS2017.SIMSService.Element[]> GetElementsBySiteAndReportAsync(string site_no, string agency_cd, string report_tp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISIMSServiceChannel : SIMS2017.SIMSService.ISIMSService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SIMSServiceClient : System.ServiceModel.ClientBase<SIMS2017.SIMSService.ISIMSService>, SIMS2017.SIMSService.ISIMSService {
        
        public SIMSServiceClient() {
        }
        
        public SIMSServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SIMSServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SIMSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SIMSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SIMS2017.SIMSService.Site[] GetAllSites() {
            return base.Channel.GetAllSites();
        }
        
        public System.Threading.Tasks.Task<SIMS2017.SIMSService.Site[]> GetAllSitesAsync() {
            return base.Channel.GetAllSitesAsync();
        }
        
        public SIMS2017.SIMSService.Site[] GetSiteByNumber(string site_no) {
            return base.Channel.GetSiteByNumber(site_no);
        }
        
        public System.Threading.Tasks.Task<SIMS2017.SIMSService.Site[]> GetSiteByNumberAsync(string site_no) {
            return base.Channel.GetSiteByNumberAsync(site_no);
        }
        
        public SIMS2017.SIMSService.Element[] GetElementsBySite(string site_no) {
            return base.Channel.GetElementsBySite(site_no);
        }
        
        public System.Threading.Tasks.Task<SIMS2017.SIMSService.Element[]> GetElementsBySiteAsync(string site_no) {
            return base.Channel.GetElementsBySiteAsync(site_no);
        }
        
        public SIMS2017.SIMSService.Element[] GetElementsBySiteAndReport(string site_no, string agency_cd, string report_tp) {
            return base.Channel.GetElementsBySiteAndReport(site_no, agency_cd, report_tp);
        }
        
        public System.Threading.Tasks.Task<SIMS2017.SIMSService.Element[]> GetElementsBySiteAndReportAsync(string site_no, string agency_cd, string report_tp) {
            return base.Channel.GetElementsBySiteAndReportAsync(site_no, agency_cd, report_tp);
        }
    }
}
